server:
  port: 8200

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot-chat
          group: comments-chat
          content-type: application/json
        #newComments:
        #  destination: learning-spring-boot-chat
        #  group: comments-chat
        #  content-type: application/json
        clientToBroker:
          destination: learning-spring-boot-chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: learning-spring-boot-chat-user-messages
          group: topic-chatMessages
    gateway:
      routes:
      #=============================================
        - id: imageService
          uri: lb://IMAGES
          predicates:
          - Path=/imageService/**
          filters:
          - RewritePath=/imageService/(?<segment>.*), /$\{segment}
          - RewritePath=/imageService, /
          - SaveSession
        - id: images
          uri: lb://IMAGES
          predicates:
          - Path=/image/**
          filters:
          - SaveSession
        - id: mainCss
          uri: lb://IMAGES
          predicates:
          - Path=/main.css
          filters:
          - SaveSession
        - id: commentService
          uri: lb://IMAGES
          predicates:
          - Path=/comments/**
          filters:
          - SaveSession
